### PR TITLE
Switch from babel to swc and sass to sass-embedded

### PR DESCRIPTION
**Pull request by puehringer**
### Summary of changes

- Improves webpack build speed because of two changes:
  - use swc-loader instead of babel-loader: swc-loader is a rust implementation and therefore much faster, however it might not be 100% compatible with our current stack. I.e. we enabled decorators explicitly (which babel has by default). 
  - use sass-embedded instead of sass: sass is a JS implementation of sass (ported via dart2js), whereas sass-embedded is an embedded version of the original (faster) dart implementation. Should be backwards compatible.

### Additional notes for the reviewer(s)

First, run `time yarn run webpack:prod` and note the time it takes to compile the entire project (around 20-80s). 

To test this new feature, simply add the following to your **resolutions** in the package.json (**not** the dependencies, as we want this branch to be used as override for all dependencies) and run `rm -rf node_modules yarn.lock && yarn`.
```
"visyn_scripts": "git+ssh://git@github.com/datavisyn/visyn_scripts.git#swc_and_sass_embedded"
```

Then, do a `rm -rf node_modules/.cache` (for a fair comparison) and `time yarn run webpack:prod` and compare it with the time before. With `http-server ./bundles --proxy http://localhost:9000 --port 8080` you can launch a http-server on the bundles folder. Everything should look and work as expected/before.

In addition to that, use `yarn start` to simply start a development server and play around, it should feel faster. 

Please post the application + before and after times here + any errors that were triggered when building/starting (maybe we are still missing some flags like decorator support). If anything had to be fixed, simply create a PR linking to this ticket. And finally add your PR/done mark to the repo sheet! 

**EDIT**
- clear the browser cache before testing it
- the changes in the webpack.config were not applied for me (I checked node_modules/visyn_scripts/config/webpack.config for "swc-loader and could not find it), so I just deleted the whole node_modules folder and yarn.lock file and then re-installed the dependencies
- Further things to consider (by Michael Puehringer): Have you opened the console and disabled caching when accessing the url? Used the correct port (it might start at 8081)? Also, have you cleared the node_modules/.cache before running the timings, as them being so low and the same is very unlikely.

### CODE REVIEW

**Comment by dvdanielamoitzi** [comment]
**Triage** 
before: 36s
after: 35s
When opening the database info detail view (or cluster compare / cluster consolidation views), i get the following error:
image

**Comment by puehringer** [comment]
@dvdanielamoitzi That is weird to happen for triage, in my tests it looks like this: 

Left is old with 63s, and right is new with 45s. I also don't get any chunk errors (although not beyond the landing page). Have you opened the console and disabled caching when accessing the url? Used the correct port (it might start at 8081)? Also, have you cleared the `node_modules/.cache` before running the timings, as them being so low and the same is very unlikely. 
image

**Comment by dvdanielamoitzi** [comment]
> @dvdanielamoitzi That is weird to happen for triage, in my tests it looks like this:
> 
> Left is old with 63s, and right is new with 45s. I also don't get any chunk errors (although not beyond the landing page). Have you opened the console and disabled caching when accessing the url? Used the correct port (it might start at 8081)? Also, have you cleared the `node_modules/.cache` before running the timings, as them being so low and the same is very unlikely. image


The only thing I did not do was disabling the cache in the console. I'll try again later!

**Comment by dvdanielamoitzi** [comment]
**HIDDEN:**
before: 35s
image
after: 35s
image


App works fine :+1:

**Comment by dv-usama-ansari** [comment]
### AELIXIR:

Before: `58.37s`

Screenshot from 2022-12-19 14-31-23

---

After: `46.40s`
image

**Comment by dv-usama-ansari** [comment]
### REPROVISYN

Before `44.89s`

Screenshot from 2022-12-19 14-39-34

---

After `31.99s`

image

**Comment by dvtschachinger** [comment]
### dTiles

Before: 34.25s
Screenshot from 2023-01-10 09-04-28

After: 25.65s
Screenshot from 2023-01-10 09-07-43

**Comment by dvdanielamoitzi** [comment]
**Sightline**

Before:
47,74s
image

After:
35,53s
image

**Comment by dvtschachinger** [comment]
### Jamborees

Before: 36.74
Screenshot from 2023-01-10 11-05-45

After: 24.80s
Screenshot from 2023-01-10 11-09-11

**Comment by dvtschachinger** [comment]
### Target360

before: 68.44
Screenshot from 2023-01-10 15-00-45

after: 58.27
Screenshot from 2023-01-10 15-02-32

**Comment by dvtschachinger** [comment]
### Disease360

before: 55.71s
Screenshot from 2023-01-11 08-20-29

after: 46.37s
Screenshot from 2023-01-11 08-23-57

**Pull request merged**
