### PR TITLE
deps: Upgrade TypeScript to ~5.1.6

### PR DESCRIPTION
**Pull request by puehringer**
### Developer Checklist (Definition of Done)

**Issue**

- [ ] All acceptance criteria from the issue are met
- [ ] Tested in latest Chrome/Firefox

**UI/UX/Vis**

- [ ] Requires UI/UX/Vis review
  - [ ] Reviewer(s) are notified (_tag assignees_)
  - [ ] Review has occurred (_link to notes_)
  - [ ] Feedback is included in this PR
  - [ ] Reviewer(s) approve of concept and design

**Code**

- [ ] Branch is up-to-date with the branch to be merged with, i.e., develop
- [ ] Code is cleaned up and formatted
- [ ] Unit tests are written (frontend/backend if applicable)
- [ ] Integration tests are written (if applicable)

**PR**

- [ ] Descriptive title for this pull request is provided (will be used for release notes later)
- [ ] Reviewer and assignees are defined
- [ ] Add type label (e.g., *bug*, *feature*) to this pull request
- [ ] Add release label (e.g., `release: minor`) to this PR following [semver](https://semver.org/)
- [ ] The PR is connected to the corresponding issue (via `Closes #...`)
- [ ] [Summary of changes](#summary-of-changes) is written

### Summary of changes

- 

### Additional notes for the reviewer(s)

-  
Thanks for creating this pull request 🤗

### CODE REVIEW

**Comment by thinkh** [comment]
Meanwhile Typescript 5.2.2 has been released. I updated the Typescript version in the package.json and the PR title accordingly. In Ordino Enterprise the new Typescript version works without problems.

**Comment by thinkh** [comment]
The CI fails with Typescript 5.2 because of the following error:

```
➜  standalone_template git:(mp/upgrade_ts_5_1_6) ✗ yarn run cy:run
Your configFile is invalid: /home/holger/w/datavisyn/visyn_scripts/tests_fixtures/standalone_template/cypress.config.ts

It threw an error when required, check the stack trace below:

TSError: ⨯ Unable to compile TypeScript:
error TS5110: Option 'module' must be set to 'NodeNext' when option 'moduleResolution' is set to 'NodeNext'.

    at createTSError (/home/holger/.cache/Cypress/12.12.0/Cypress/resources/app/node_modules/ts-node/dist/index.js:311:16)
    at reportTSError (/home/holger/.cache/Cypress/12.12.0/Cypress/resources/app/node_modules/ts-node/dist/index.js:314:23)
    at /home/holger/.cache/Cypress/12.12.0/Cypress/resources/app/node_modules/ts-node/dist/index.js:686:17
    at Object.compile (/home/holger/.cache/Cypress/12.12.0/Cypress/resources/app/node_modules/ts-node/dist/index.js:743:35)
    at Module.m._compile (/home/holger/.cache/Cypress/12.12.0/Cypress/resources/app/node_modules/ts-node/dist/index.js:856:36)
    at Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Object.require.extensions.<computed> [as .ts] (/home/holger/.cache/Cypress/12.12.0/Cypress/resources/app/node_modules/ts-node/dist/index.js:859:16)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at loadFile (/home/holger/.cache/Cypress/12.12.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_require_async_child.js:89:14)
    at EventEmitter.<anonymous> (/home/holger/.cache/Cypress/12.12.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_require_async_child.js:116:38)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.emit (node:domain:489:12)
    at process.<anonymous> (/home/holger/.cache/Cypress/12.12.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/util.js:33:22)
```

The change is noted in the [Typescript 5.2 release notes](https://devblogs.microsoft.com/typescript/announcing-typescript-5-2/#module-and-moduleresolution-must-match-under-recent-node-js-settings). More information can be found in [this Github PR](https://github.com/microsoft/TypeScript/pull/54567).

I revert the Typescript version to ~5.1.6 and we make the switch to Typescript 5.2 in a different.

**Comment by dvtschachinger** [comment]
Needed to do some [fixes](https://github.com/datavisyn/aelixir/pull/611) in Älixir. Marketplace360 runs through. Added the infos to the repo sheet.

**Comment by dvmartinweigl** [comment]
I tested this branch on Bioinsight, Sightline, Hts_Hidden, Triage and all of the ran throught without any errors.

**Review by thinkh — APPROVED** [review]
It was tested successfully in all apps. 👍

**Pull request merged**
